name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Node.js (caso seja necessário)
    #- name: Set up Node.js
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: '16' # Escolha a versão de Node.js compatível

    # Instalar dependências (caso use um gerenciador de pacotes como npm ou yarn)
    #- name: Install dependencies
    #  run: npm install

    # Construir o projeto (caso seja necessário)
    #- name: Build the project
    #  run: npm run build

    # Deploy para GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
